config/routes.rb
Playground::Application.routes.draw do
  resources :creatives

end

app/models/creative.rb
class Creative
  include Mongoid::Document
  field :name, type: String
  field :url, type: String

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController

  def index
    @creatives = Creative.all
  end

  def show
    @creative = Creative.find(params[:id])
  end

  def new
    @creative = Creative.new
  end

  def edit
    @creative = Creative.find(params[:id])
  end

  def create
    @creative = Creative.new(params[:creative])

    if @creative.save
      redirect_to @creative, notice: 'Creative was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @creative = Creative.find(params[:id])

    if @creative.update_attributes(params[:creative])
      redirect_to @creative, notice: 'Creative was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @creative = Creative.find(params[:id])
    @creative.destroy

    redirect_to creatives_url, notice: 'Creative was successfully deleted.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatives_helper.rb
module CreativesHelper
end

app/views/creatives/_form.html.haml
= simple_form_for(@creative) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :url
    = f.input :image

  .form-actions
    = f.button :submit

app/views/creatives/edit.html.haml
%h1 Editing creative

= render 'form'

= link_to 'Show', @creative
\|
= link_to 'Back', creatives_path

app/views/creatives/index.html.haml
%h1 Listing creatives

%table.table.table-striped.table-bordered

  %thead
    %tr
      %th Name
      %th Url
      %th
      %th
      %th

  %tbody
    - @creatives.each do |creative|
      %tr
        %td= creative.name
        %td= creative.url
        %td= link_to 'Show', creative
        %td= link_to 'Edit', edit_creative_path(creative)
        %td= link_to 'Destroy', creative, method: :delete, data: { confirm: 'Are you sure?' }

%br/

= link_to new_creative_path, :class => 'btn btn-primary' do
  %i.icon-plus
  New Creative

app/views/creatives/new.html.haml
%h1 New creative

= render 'form'

= link_to 'Back', creatives_path

app/views/creatives/show.html.haml
%p
  %b Name:
  = @creative.name

%p
  %b Url:
  = @creative.url

= link_to 'Edit', edit_creative_path(@creative)
\|
= link_to 'Back', creatives_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/application.html.haml
!!! Strict
%html{:lang => "en"}
  %head
    %meta{charset: "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=IE7"}
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
    %title Playground
    = csrf_meta_tags
    /[if lt IE 9]
      %script(src="http://html5shiv.googlecode.com/svn/trunk/html5.js")

    = stylesheet_link_tag "application", :media => "all"

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{href: "#"} Playground
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link1", "/path1"
              %li= link_to "Link2", "/path2"
              %li= link_to "Link3", "/path3"

    .container

      .content
        .row
          .span9
            = render 'layouts/messages'
            = yield
          .span3
            .well.sidebar-nav
              %h3 Sidebar
              %ul.nav.nav-list
                %li.nav-header Sidebar
                %li= link_to "Link1", "/path1"
                %li= link_to "Link2", "/path2"
                %li= link_to "Link3", "/path3"

      %footer
        %p © Company 2012

    = javascript_include_tag "application"